//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickSell.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cell
    {
        public Cell()
        {
            this.Childs = new HashSet<Cell>();
            this.Seats = new HashSet<Seat>();
            this.TimeCells = new HashSet<TimeCell>();
        }
    
        public System.Guid ID { get; set; }
        public string CellName { get; set; }
        public string CellText { get; set; }
        public string CreatDate { get; set; }
        public Nullable<System.Guid> CreaterId { get; set; }
        public int ColNum { get; set; }
        public int RowNum { get; set; }
        public Nullable<System.Guid> Father { get; set; }
    
        public virtual ICollection<Cell> Childs { get; set; }
        public virtual Cell CellParent { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Seat> Seats { get; set; }
        public virtual ICollection<TimeCell> TimeCells { get; set; }
    }
}
