//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickSell.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeCell
    {
        public TimeCell()
        {
            this.TimeCellSeats = new HashSet<TimeCellSeat>();
        }
    
        public System.Guid ID { get; set; }
        public System.DateTime TimeBe { get; set; }
        public System.DateTime TimeEn { get; set; }
        public string MovieName { get; set; }
        public Nullable<System.Guid> CellID { get; set; }
        public int ColNum { get; set; }
        public int RowNum { get; set; }
        public string ShowTimes { get; set; }
    
        public virtual Cell Cell { get; set; }
        public virtual ICollection<TimeCellSeat> TimeCellSeats { get; set; }
    }
}
