//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickSell.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeCellSeat
    {
        public System.Guid ID { get; set; }
        public string SeatName { get; set; }
        public bool IsSold { get; set; }
        public bool IsUsing { get; set; }
        public string CreatDate { get; set; }
        public int RowIndex { get; set; }
        public int ColIndex { get; set; }
        public int SeatIndex { get; set; }
        public Nullable<System.Guid> TimeCellID { get; set; }
        public string SeatType { get; set; }
        public string TicketType { get; set; }
        public Nullable<double> TicketPrice { get; set; }
        public Nullable<System.Guid> SoldUserID { get; set; }
    
        public virtual TimeCell TimeCell { get; set; }
        public virtual User SoldUser { get; set; }
    }
}
